version: "3.7"

services:
  # Postgres
  postgres:
    environment:
      POSTGRES_USER: <user>
      POSTGRES_PASSWORD: <password>
      POSTGRES_URL: postgres://<user>:<password>@localhost:5432/<db>
      POSTGRES_DB: <db>
      POSTGRES_HOST: postgres
    build: ./sql
    ports:
      - "5433:5432"

  # Redis
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"

  # Backend
  auther:
    container_name: backend
    build: ./
    command: npm run app:dev
    working_dir: /usr/src/auther/server
    environment:
      DEBUG_COLORS: 1
      POSTGRES_URI: postgres://<user>:<password>@postgres:5432/<db>
      REDIS_URI: redis://redis:6379
    ports:
      - "5000:5000"
    volumes:
      - ./server:/usr/src/auther/server

  # Frontend
  client:
    container_name: client
    build: ./client
    command: npm run dev
    ports:
      - "5001:5001"
    volumes:
      - ./client:/usr/src/auther/client
